base_url = "https://tekne.dev"
title = "tekne.dev"
author = "Jad Ghalayini"
description = "Jad Ghalayini's devlog"
theme = "dose"

compile_sass = true
build_search_index = true
minify_html = true

[markdown]
highlight_code = true

[extra]
social_media = [
    { name = "gitlab", url = "https://gitlab.com/tekne", icon = "fa-brands fa-gitlab" },
    { name = "github", url = "https://github.com/imbrem", icon = "fa-brands fa-github" },
    { name = "email", url = "mailto:jeg74@cl.cam.ac.uk", icon = "fa-solid fa-envelope" }
]