import Mathlib.Tactic

universe u v w

namespace ProjectBeth.STLC.Syntax

/-- A signature for first-order type constructors. -/
structure Signature where
  Op : Type u
  arity : Op → Nat

structure Signature.Hom (S T : Signature) where
  onOp : S.Op → T.Op
  arity_eq : ∀ f, T.arity (onOp f) = S.arity f

/-- The free type algebra generated by base types and a constructor signature. -/
inductive TypeExpr (S : Signature.{u}) (Base : Type v) : Type (max u v)
  | base : Base → TypeExpr S Base
  | op (f : S.Op) : (Fin (S.arity f) → TypeExpr S Base) → TypeExpr S Base

variable {S T : Signature.{u}} {Base : Type v} {Base' : Type w} {X Y : Type*}

def TypeExpr.fold (base : Base → X)
    (op : ∀ f : S.Op, (Fin (S.arity f) → X) → X) : TypeExpr S Base → X
  | .base b => base b
  | .op f xs => op f (fun i => (xs i).fold base op)

def TypeExpr.map (f : Base → Base') : TypeExpr S Base → TypeExpr S Base'
  | .base b => .base (f b)
  | .op o xs => .op o (fun i => (xs i).map f)

def TypeExpr.bind (f : Base → TypeExpr S Base') : TypeExpr S Base → TypeExpr S Base'
  | .base b => f b
  | .op o xs => .op o (fun i => (xs i).bind f)

theorem TypeExpr.map_eq_bind (f : Base → Base') (A : TypeExpr S Base) :
    A.map f = A.bind (.base ∘ f) := by
  induction A with
  | base => rfl
  | op o xs ih => simp only [map, bind]; congr; funext i; exact ih i

def TypeExpr.mapOps (F : Signature.Hom S T) : TypeExpr S Base → TypeExpr T Base
  | .base b => .base b
  | .op f xs => .op (F.onOp f) (fun i =>
      (xs (Fin.cast (F.arity_eq f) i)).mapOps F)

@[simp] theorem TypeExpr.fold_base (base : Base → X)
    (op : ∀ f : S.Op, (Fin (S.arity f) → X) → X) (b : Base) :
    (TypeExpr.base b : TypeExpr S Base).fold base op = base b := rfl

@[simp] theorem TypeExpr.fold_op {Base : Type v} {X : Type w}
    (base : Base → X) (op : ∀ f : S.Op, (Fin (S.arity f) → X) → X)
    (f : S.Op) (xs : Fin (S.arity f) → TypeExpr S Base) :
    (TypeExpr.op f xs).fold base op = op f (fun i => (xs i).fold base op) := rfl

namespace Arrow

inductive Op | arr
  deriving DecidableEq

abbrev signature : Signature := ⟨Op, fun _ => 2⟩

/-- Concrete arrow-only simple types. -/
inductive Ty (Base : Type v) : Type v
  | base : Base → Ty Base
  | arr : Ty Base → Ty Base → Ty Base

private def args (A B : X) : Fin 2 → X :=
  Fin.cases A (Fin.cases B Fin.elim0)

@[simp] private theorem args_zero (A B : X) : args A B 0 = A := rfl
@[simp] private theorem args_one (A B : X) : args A B 1 = B := rfl
private theorem args_eta (xs : Fin 2 → X) : args (xs 0) (xs 1) = xs := by
  funext i
  exact Fin.cases rfl (fun j => Fin.cases rfl (fun k => Fin.elim0 k) j) i
private theorem args_map (f : X → Y) (A B : X) :
    args (f A) (f B) = fun i => f (args A B i) := by
  funext i
  exact Fin.cases rfl (fun j => Fin.cases rfl (fun k => Fin.elim0 k) j) i

def toExpr : Ty Base → TypeExpr signature Base
  | .base b => .base b
  | .arr A B => .op .arr (args (toExpr A) (toExpr B))

def fromExpr : TypeExpr signature Base → Ty Base
  | .base b => .base b
  | .op .arr xs => .arr (fromExpr (xs 0)) (fromExpr (xs 1))

@[simp] theorem fromExpr_toExpr (A : Ty Base) : fromExpr (toExpr A) = A := by
  induction A with
  | base => rfl
  | arr A B ihA ihB => simp [toExpr, fromExpr, args_zero, args_one, ihA, ihB]

@[simp] theorem toExpr_fromExpr (A : TypeExpr signature Base) :
    toExpr (fromExpr A) = A := by
  induction A with
  | base => rfl
  | op f xs ih =>
    cases f
    simp only [fromExpr, toExpr]
    have hargs : args (toExpr (fromExpr (xs 0)))
        (toExpr (fromExpr (xs 1))) = xs := by
      rw [ih 0, ih 1]
      exact args_eta xs
    rw [hargs]

def exprEquiv : Ty Base ≃ TypeExpr signature Base where
  toFun := toExpr
  invFun := fromExpr
  left_inv := fromExpr_toExpr
  right_inv := toExpr_fromExpr

def fold (base : Base → X) (arr : X → X → X) : Ty Base → X
  | .base b => base b
  | .arr A B => arr (fold base arr A) (fold base arr B)

def subst (σ : Base → Ty Base') : Ty Base → Ty Base'
  | .base b => σ b
  | .arr A B => .arr (subst σ A) (subst σ B)

def rename (ρ : Base → Base') : Ty Base → Ty Base' :=
  subst (.base ∘ ρ)

theorem toExpr_subst (σ : Base → Ty Base') (A : Ty Base) :
    toExpr (subst σ A) = (toExpr A).bind (toExpr ∘ σ) := by
  induction A with
  | base => rfl
  | arr A B ihA ihB =>
    simp only [subst, toExpr, TypeExpr.bind, ihA, ihB]
    rw [args_map]

theorem toExpr_rename (ρ : Base → Base') (A : Ty Base) :
    toExpr (rename ρ A) = (toExpr A).map ρ := by
  rw [rename, toExpr_subst, TypeExpr.map_eq_bind]
  rfl

private def foldOp (arr : X → X → X) :
    ∀ f : Op, (Fin (signature.arity f) → X) → X
  | .arr, xs => arr (xs 0) (xs 1)

theorem toExpr_fold (base : Base → X) (arr : X → X → X) (A : Ty Base) :
    (toExpr A).fold base (foldOp arr) =
      fold base arr A := by
  induction A <;> simp [toExpr, fold, foldOp, args_zero, args_one, *]

end Arrow

namespace HighSchool

/-- Products, sums, and function-space exponentials. -/
inductive Op | prod | sum | arr
  deriving DecidableEq

abbrev signature : Signature := ⟨Op, fun _ => 2⟩

/-- Concrete products, sums, and function-space exponentials. -/
inductive Ty (Base : Type v) : Type v
  | base : Base → Ty Base
  | prod : Ty Base → Ty Base → Ty Base
  | sum : Ty Base → Ty Base → Ty Base
  | arr : Ty Base → Ty Base → Ty Base

private def args (A B : TypeExpr signature Base) : Fin 2 → TypeExpr signature Base
  := Fin.cases A (Fin.cases B Fin.elim0)

@[simp] private theorem args_zero (A B : TypeExpr signature Base) : args A B 0 = A := rfl
@[simp] private theorem args_one (A B : TypeExpr signature Base) : args A B 1 = B := rfl
private theorem args_eta (xs : Fin 2 → X) :
    (Fin.cases (xs 0) (Fin.cases (xs 1) Fin.elim0)) = xs := by
  funext i
  exact Fin.cases rfl (fun j => Fin.cases rfl (fun k => Fin.elim0 k) j) i
private theorem args_natural (f : TypeExpr signature Base → TypeExpr signature Base')
    (A B : TypeExpr signature Base) :
    args (f A) (f B) = fun i => f (args A B i) := by
  funext i
  exact Fin.cases rfl (fun j => Fin.cases rfl (fun k => Fin.elim0 k) j) i

def toExpr : Ty Base → TypeExpr signature Base
  | .base b => .base b
  | .prod A B => .op .prod (args (toExpr A) (toExpr B))
  | .sum A B => .op .sum (args (toExpr A) (toExpr B))
  | .arr A B => .op .arr (args (toExpr A) (toExpr B))

def fromExpr : TypeExpr signature Base → Ty Base
  | .base b => .base b
  | .op .prod xs => .prod (fromExpr (xs 0)) (fromExpr (xs 1))
  | .op .sum xs => .sum (fromExpr (xs 0)) (fromExpr (xs 1))
  | .op .arr xs => .arr (fromExpr (xs 0)) (fromExpr (xs 1))

@[simp] theorem fromExpr_toExpr (A : Ty Base) : fromExpr (toExpr A) = A := by
  induction A <;> simp [toExpr, fromExpr, args_zero, args_one, *]

@[simp] theorem toExpr_fromExpr (A : TypeExpr signature Base) :
    toExpr (fromExpr A) = A := by
  induction A with
  | base => rfl
  | op f xs ih =>
    cases f <;> simp only [fromExpr, toExpr] <;>
      apply congrArg (TypeExpr.op _) <;> rw [ih 0, ih 1] <;> exact args_eta xs

def exprEquiv : Ty Base ≃ TypeExpr signature Base where
  toFun := toExpr
  invFun := fromExpr
  left_inv := fromExpr_toExpr
  right_inv := toExpr_fromExpr

def fold (base : Base → X) (prod sum arr : X → X → X) : Ty Base → X
  | .base b => base b
  | .prod A B => prod (fold base prod sum arr A) (fold base prod sum arr B)
  | .sum A B => sum (fold base prod sum arr A) (fold base prod sum arr B)
  | .arr A B => arr (fold base prod sum arr A) (fold base prod sum arr B)

def subst (σ : Base → Ty Base') : Ty Base → Ty Base'
  | .base b => σ b
  | .prod A B => .prod (subst σ A) (subst σ B)
  | .sum A B => .sum (subst σ A) (subst σ B)
  | .arr A B => .arr (subst σ A) (subst σ B)

def rename (ρ : Base → Base') : Ty Base → Ty Base' :=
  subst (.base ∘ ρ)

theorem toExpr_subst (σ : Base → Ty Base') (A : Ty Base) :
    toExpr (subst σ A) = (toExpr A).bind (toExpr ∘ σ) := by
  induction A with
  | base => rfl
  | prod A B ihA ihB | sum A B ihA ihB | arr A B ihA ihB =>
    simp only [subst, toExpr, TypeExpr.bind, ihA, ihB]
    rw [args_natural]

theorem toExpr_rename (ρ : Base → Base') (A : Ty Base) :
    toExpr (rename ρ A) = (toExpr A).map ρ := by
  rw [rename, toExpr_subst, TypeExpr.map_eq_bind]
  rfl

private def foldOp (prod sum arr : X → X → X) :
    ∀ f : Op, (Fin (signature.arity f) → X) → X
  | .prod, xs => prod (xs 0) (xs 1)
  | .sum, xs => sum (xs 0) (xs 1)
  | .arr, xs => arr (xs 0) (xs 1)

theorem toExpr_fold (base : Base → X) (prod sum arr : X → X → X) (A : Ty Base) :
    (toExpr A).fold base (foldOp prod sum arr) = fold base prod sum arr A := by
  induction A <;>
    simp [toExpr, fold, foldOp, args_zero, args_one, *]

end HighSchool

namespace ArrowHighSchool

def opInclusion : Signature.Hom Arrow.signature HighSchool.signature where
  onOp := fun | .arr => .arr
  arity_eq := by intro f; cases f; rfl

def embed : Arrow.Ty Base → HighSchool.Ty Base
  | .base b => .base b
  | .arr A B => .arr (embed A) (embed B)

def project? : HighSchool.Ty Base → Option (Arrow.Ty Base)
  | .base b => some (.base b)
  | .arr A B => return .arr (← project? A) (← project? B)
  | .prod _ _ | .sum _ _ => none

@[simp] theorem project_embed (A : Arrow.Ty Base) : project? (embed A) = some A := by
  induction A with
  | base => rfl
  | arr A B ihA ihB => simp [embed, project?, ihA, ihB]

theorem toExpr_embed (A : Arrow.Ty Base) :
    HighSchool.toExpr (embed A) = (Arrow.toExpr A).mapOps opInclusion := by
  induction A with
  | base => rfl
  | arr A B ihA ihB =>
    simp only [embed, HighSchool.toExpr, Arrow.toExpr, TypeExpr.mapOps]
    congr
    funext i
    exact Fin.cases ihA (fun j => Fin.cases ihB (fun k => Fin.elim0 k) j) i

private theorem embed_of_project (B : HighSchool.Ty Base) :
    ∀ {A : Arrow.Ty Base}, project? B = some A → embed A = B := by
  induction B with
  | base b => intro A h; simp [project?] at h; cases h; rfl
  | prod => simp [project?]
  | sum => simp [project?]
  | arr B C ihB ihC =>
    intro A h
    cases hB : project? B with
    | none => simp [project?, hB] at h
    | some A₁ =>
      cases hC : project? C with
      | none => simp [project?, hB, hC] at h
      | some A₂ =>
        simp [project?, hB, hC] at h
        cases h
        exact congrArg₂ HighSchool.Ty.arr (ihB hB) (ihC hC)

theorem project_eq_some_iff (B : HighSchool.Ty Base) (A : Arrow.Ty Base) :
    project? B = some A ↔ embed A = B := by
  constructor
  · exact embed_of_project B
  · rintro rfl
    exact project_embed A

theorem fold_embed (base : Base → X) (arr : X → X → X)
    (prod sum : X → X → X) (A : Arrow.Ty Base) :
    HighSchool.fold base prod sum arr (embed A) = Arrow.fold base arr A := by
  induction A <;> simp [embed, HighSchool.fold, Arrow.fold, *]

end ArrowHighSchool

end ProjectBeth.STLC.Syntax
